INSERT INTO DIM_GESCHLECHT (geschlecht_id, geschlecht_name)
SELECT DISTINCT SEX,
       CASE SEX
           WHEN 0 THEN 'total'
           WHEN 1 THEN 'männlich'
           WHEN 2 THEN 'weiblich'
           END
FROM "STAGING_OOE_Bev_Geschl_Alt5J";

INSERT INTO DIM_ALTERSGRUPPE (altersgruppe_id, von, bis)
    SELECT 'AGE_0_TO_4', 0, 4 FROM DUAL UNION ALL
    SELECT 'AGE_5_TO_9', 5, 9 FROM DUAL UNION ALL
    SELECT 'AGE_10_TO_14', 10, 14 FROM DUAL UNION ALL
    SELECT 'AGE_15_TO_19', 15, 19 FROM DUAL UNION ALL
    SELECT 'AGE_20_TO_24', 20, 24 FROM DUAL UNION ALL
    SELECT 'AGE_25_TO_29', 25, 29 FROM DUAL UNION ALL
    SELECT 'AGE_30_TO_34', 30, 34 FROM DUAL UNION ALL
    SELECT 'AGE_35_TO_39', 35, 39 FROM DUAL UNION ALL
    SELECT 'AGE_40_TO_44', 40, 44 FROM DUAL UNION ALL
    SELECT 'AGE_45_TO_49', 45, 49 FROM DUAL UNION ALL
    SELECT 'AGE_50_TO_54', 50, 54 FROM DUAL UNION ALL
    SELECT 'AGE_55_TO_59', 55, 59 FROM DUAL UNION ALL
    SELECT 'AGE_60_TO_64', 60, 64 FROM DUAL UNION ALL
    SELECT 'AGE_65_TO_69', 65, 69 FROM DUAL UNION ALL
    SELECT 'AGE_70_TO_74', 70, 74 FROM DUAL UNION ALL
    SELECT 'AGE_75_TO_79', 75, 79 FROM DUAL UNION ALL
    SELECT 'AGE_80_TO_84', 80, 84 FROM DUAL UNION ALL
    SELECT 'AGE_85_TO_89', 85, 89 FROM DUAL UNION ALL
    SELECT 'AGE_90_TO_94', 90, 94 FROM DUAL UNION ALL
    SELECT 'AGE_95_TO_99', 95, 99 FROM DUAL UNION ALL
    SELECT 'AGE_90_PLUS', 90, 1000 FROM DUAL UNION ALL
    SELECT 'AGE_100_PLUS', 100, 1000 FROM DUAL;

INSERT INTO DIM_ZEITRAUM
SELECT DISTINCT YEAR FROM "STAGING_OOE_Bevoelkerung_Zeitreihe";

INSERT INTO DIM_GEMEINDEN (LAU2_CODE, LAU2_NAME)
SELECT DISTINCT LAU2_CODE, TO_CHAR(LAU2_NAME)
FROM "STAGING_OOE_Bevoelkerung_Zeitreihe";

INSERT INTO DIM_STAATSANGEHOERIGKEIT (STAATSANGEHOERIGKEIT_ID, STAATSANGEHOERIGKEIT_NAME)
    SELECT 'AT', 'NATION_AUSTRIA' FROM DUAL UNION ALL
    SELECT 'FE', 'NATION_FOREIGN' FROM DUAL UNION ALL
    SELECT 'TOT', 'NATION_TOTAL' FROM DUAL UNION ALL
    SELECT 'EU', 'NATION_EU' FROM DUAL UNION ALL
    SELECT 'FYS', 'NATION_FORMER_YUGOSLAVIA' FROM DUAL UNION ALL
    SELECT 'TR', 'NATION_TURKEY'  FROM DUAL UNION ALL
    SELECT 'OTH', 'NATION_OTHERS' FROM DUAL;


INSERT INTO FAKT_GESAMTBEVOELKERUNG (geschlecht_id, altersgruppe_id, jahr, LAU2_CODE, staatsangehoerigkeit_id, bevoelkerungsanzahl)
SELECT sex, 'AGE_0_TO_4', year, LAU2_CODE, NULL, AGE_0_TO_4 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_5_TO_9', year, LAU2_CODE, NULL, AGE_5_TO_9 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_10_TO_14', year, LAU2_CODE, NULL, AGE_10_TO_14 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_15_TO_19', year, LAU2_CODE, NULL, AGE_15_TO_19 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_20_TO_24', year, LAU2_CODE, NULL, AGE_20_TO_24 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_25_TO_29', year, LAU2_CODE, NULL, AGE_25_TO_29 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_30_TO_34', year, LAU2_CODE, NULL, AGE_30_TO_34 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_35_TO_39', year, LAU2_CODE, NULL, AGE_35_TO_39 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_40_TO_44', year, LAU2_CODE, NULL, AGE_40_TO_44 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_45_TO_49', year, LAU2_CODE, NULL, AGE_45_TO_49 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_50_TO_54', year, LAU2_CODE, NULL, AGE_50_TO_54 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_55_TO_59', year, LAU2_CODE, NULL, AGE_55_TO_59 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_60_TO_64', year, LAU2_CODE, NULL, AGE_60_TO_64 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_65_TO_69', year, LAU2_CODE, NULL, AGE_65_TO_69 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_70_TO_74', year, LAU2_CODE, NULL, AGE_70_TO_74 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_75_TO_79', year, LAU2_CODE, NULL, AGE_75_TO_79 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_80_TO_84', year, LAU2_CODE, NULL, AGE_80_TO_84 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_85_TO_89', year, LAU2_CODE, NULL, AGE_85_TO_89 FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_90_PLUS', year, LAU2_CODE, NULL, AGE_90_PLUS FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Geschl_Alt5J" UNION ALL

SELECT sex, 'AGE_0_TO_4', year, LAU2_CODE, NULL, AGE_0_TO_4 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_5_TO_9', year, LAU2_CODE, NULL, AGE_5_TO_9 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_10_TO_14', year, LAU2_CODE, NULL, AGE_10_TO_14 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_15_TO_19', year, LAU2_CODE, NULL, AGE_15_TO_19 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_20_TO_24', year, LAU2_CODE, NULL, AGE_20_TO_24 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_25_TO_29', year, LAU2_CODE, NULL, AGE_25_TO_29 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_30_TO_34', year, LAU2_CODE, NULL, AGE_30_TO_34 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_35_TO_39', year, LAU2_CODE, NULL, AGE_35_TO_39 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_40_TO_44', year, LAU2_CODE, NULL, AGE_40_TO_44 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_45_TO_49', year, LAU2_CODE, NULL, AGE_45_TO_49 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_50_TO_54', year, LAU2_CODE, NULL, AGE_50_TO_54 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_55_TO_59', year, LAU2_CODE, NULL, AGE_55_TO_59 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_60_TO_64', year, LAU2_CODE, NULL, AGE_60_TO_64 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_65_TO_69', year, LAU2_CODE, NULL, AGE_65_TO_69 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_70_TO_74', year, LAU2_CODE, NULL, AGE_70_TO_74 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_75_TO_79', year, LAU2_CODE, NULL, AGE_75_TO_79 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_80_TO_84', year, LAU2_CODE, NULL, AGE_80_TO_84 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_85_TO_89', year, LAU2_CODE, NULL, AGE_85_TO_89 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_90_TO_94', year, LAU2_CODE, NULL, AGE_90_TO_94 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_95_TO_99', year, LAU2_CODE, NULL, AGE_95_TO_99 FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL
SELECT sex, 'AGE_100_PLUS', year, LAU2_CODE, NULL, AGE_100_PLUS FROM "STAGING_OOE_Bev_Geschl_Alt5J" UNION ALL

SELECT NULL, NULL, year, LAU2_CODE, 'AT', NATION_AUSTRIA FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'FE', NATION_FOREIGN FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'TOT', NATION_TOTAL FROM "STAGING_OOE_Bev_laut_Volkszaehlung_Staatsangehoerigkeit" UNION ALL

SELECT NULL, NULL, year, LAU2_CODE, 'EU', NATION_EU FROM "STAGING_OOE_Bev_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'FYS', NATION_FORMER_YUGOSLAVIA FROM "STAGING_OOE_Bev_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'TR', NATION_TURKEY FROM "STAGING_OOE_Bev_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'OTH', NATION_OTHERS FROM "STAGING_OOE_Bev_Staatsangehoerigkeit" UNION ALL
SELECT NULL, NULL, year, LAU2_CODE, 'TOT', NATION_TOTAL FROM "STAGING_OOE_Bev_Staatsangehoerigkeit";